import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";

export default function Home() {
	const { data: session } = useSession();

	console.log(session);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1 className='text-3xl font-bold underline text-blue-300'>
				Hello world!
			</h1>
			{session && (
				<>
					Signed in as {session.user.email} <br />
					<button onClick={() => signOut()}>Sign out</button>
				</>
			)}
			{!session && (
				<>
					Not signed in <br />
					<button onClick={() => signIn()}>Sign in</button>
				</>
			)}
			<div>
				<Link href='/post'>
					<a>post</a>
				</Link>
			</div>
		</div>
	);
}
